#!/usr/bin/perl

use LWP::Simple;
use JSON;
use Data::Dumper;
use LWP::UserAgent;

my $vip = $ARGV[0] or die "Please add <Vip> <Port> <Service> as arguments\n";
my $port = $ARGV[1] or die "Please add <Vip> <Port> <Service> as arguments\n";
my $service = $ARGV[2] or die "Please add <Vip> <Port> <Service> as arguments\n";
$service = $service . "_haproxy";

my $ua = new LWP::UserAgent();


#Verify if Haproxy has already registered vip details
my $url_v = 'http://localhost:8500/v1/kv/' . $service . '/vip_data?raw';
$response = $ua->get($url_v);
my $content = decode_json $response->{_content};

if (defined $content->{vip}) { 
print "ALREADY REGISTERED\n";
exit 0;
}
else {

#Register Haproxy service 
my $url1 = 'http://localhost:8500/v1/agent/service/register';
my $json = {"ID"=>"$service", "Name"=>"$service"};
$json = encode_json($json) ;
$response = $ua->post($url1,'Content-Type' => 'application/json',  'Content' =>$json);

#Register Vip, port details
my $url2 = 'http://localhost:8500/v1/kv/' . $service . '/vip_data';
my $json2 = {"vip"=> "$vip", "port"=> "$port"};
$json2 = encode_json($json2) ;
my $response2 = $ua->put($url2,'Content-Type' => 'application/json',  'Content' =>$json2);
checkResponse($response2);
}



sub checkResponse {
    my $response = shift;
    if ( $response->is_success() ) {
        print("SUCCESSFUL \n");
    }
    else {
        print("ERROR: " . $response->status_line());
    }
}
