#!/usr/bin/perl

use LWP::Simple;
use JSON;
use Data::Dumper;
use LWP::UserAgent;

my $vip = $ARGV[0] or die usage();
my $port = $ARGV[1] or die usage();
my $service = $ARGV[2] or die usage();
$service = $service . "-haproxy";

die "Port should be number\n" unless $port=~/^\d+$/;

my $ua = new LWP::UserAgent();

#Register Haproxy service 
my $url1 = 'http://localhost:8500/v1/agent/service/register';
my $json = {"ID"=>"$service", "Name"=>"$service", "Address"=>"$vip", "Port"=> int $port};
$json = encode_json($json) ;
$response = $ua->post($url1,'Content-Type' => 'application/json',  'Content' =>$json);
checkResponse($response);


sub checkResponse {
    my $response = shift;
    if ( $response->is_success() ) {
        print("SUCCESSFUL \n");
    }
    else {
        print("ERROR: " . $response->status_line());
    }
}

sub usage {
'Please add <Vip> <Port> <Service> as arguments

e.g:
registerHaproxyVip 10.22.75.75 9959 mp

'
}
