#!/usr/bin/perl

use LWP::Simple;
use JSON;
use Data::Dumper;
use LWP::UserAgent;
use Sys::Hostname;

my $port = $ARGV[0] or die "Please add <Port> <Service> as arguments\n";
my $service = $ARGV[1] or die "Please add <Port> <Service> as arguments\n";

my $ua = new LWP::UserAgent();

#Register Haproxy service 
my $url1 = 'http://localhost:8500/v1/agent/service/register';
my $json = {"ID"=>"$service", "Name"=>"$service", "Port"=> int $port};
$json = encode_json($json) ;
$response = $ua->post($url1,'Content-Type' => 'application/json',  'Content' =>$json);
checkResponse($response);


sub checkResponse {
    my $response = shift;
    if ( $response->is_success() ) {
        print("SUCCESSFUL \n");
    }
    else {
        print("ERROR: " . $response->status_line());
    }
}
